name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          cd /home/projects/backend
          ./gradlew build

      - name: Restart server
        run: |
          # Kill the process running on port 8080
          sudo lsof -t -i:8080 | xargs -r kill || true
          # Start the new instance in the background with nohup and logging
          cd /home/projects/backend/build/libs
          nohup sudo java -jar *SNAPSHOT.jar > app.log 2>&1 &
