name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          cd /home/projects/backend
          ./gradlew build

      - name: Prepare backend zip
        run: |
          cd /home/projects/backend
          zip -r backend.zip ./build/libs/*.jar

      - name: Copy build artifacts to target directory
        run: |
          mkdir -p /home/projects/backend/target
          cp backend.zip /home/projects/backend/target/

      - name: Stop existing application
        run: |
          sudo lsof -t -i:8080 | xargs -r kill || true

      - name: Restart server
        run: |
          cd /home/projects/backend/target
          unzip -o backend.zip
          nohup java -jar ./build/libs/backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
