name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
      - name: Prepare backend zip
        run: |
          zip -r backend.zip ./build/libs/*.jar
      - name: Copy build artifacts to target directory
        run: |
          mkdir -p /home/projects/backend
          cp backend.zip /home/projects/backend/
      - name: Stop existing application
        run: |
          sudo lsof -t -i:8080 | xargs -r kill
      - name: Restart server
        run: |
          cd /home/projects/backend
          unzip -o backend.zip
          java -jar ./build/libs/backend-0.0.1-SNAPSHOT.jar &
