name: Deploy Backend Application via Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd /home/projects/backend
          ./gradlew build

      - name: Build Docker Image
        run: |
          docker build -t username/backend-app:v${{ github.run_number }} -f /home/projects/backend/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push username/backend-app:v${{ github.run_number }}

      - name: Pull and Run Docker Container
        run: |
          docker pull username/backend-app:v${{ github.run_number }}
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 8080:8080 username/backend-app:v${{ github.run_number }}
